const QuizConfig = require("../models/quizConfig");

// Multiple quiz configs can exist at once (POST /api/quizzes/config allows it),
// so a bare QuizConfig.findOne() returns an arbitrary document - usually the
// oldest, long-expired schedule. Always resolve the config that applies now.

// The schedule that is live at `now`, if any.
async function getActiveQuizConfig(now = new Date()) {
  return QuizConfig.findOne({
    isEnable: true,
    startDate: { $lte: now },
    endDate: { $gte: now }
  }).sort({ startDate: -1 });
}

// The live schedule, or the most recent one when nothing is live. Callers that
// gate on isEnable/startDate/endDate use this so their error messages stay
// accurate ("not started yet" vs "has ended").
async function getCurrentOrLatestQuizConfig(now = new Date()) {
  const active = await getActiveQuizConfig(now);
  if (active) return active;
  return QuizConfig.findOne().sort({ startDate: -1 });
}

// The schedule a quiz belongs to. Quizzes generated by GET /api/quizzes/today
// carry quizConfigId; older quizzes may not, so fall back to the live schedule.
async function getQuizConfigForQuiz(quiz, now = new Date()) {
  if (quiz && quiz.quizConfigId) {
    const config = await QuizConfig.findById(quiz.quizConfigId);
    if (config) return config;
  }
  return getCurrentOrLatestQuizConfig(now);
}

module.exports = {
  getActiveQuizConfig,
  getCurrentOrLatestQuizConfig,
  getQuizConfigForQuiz
};
